package eps.platform.infraestructure.exception;

public enum ErrorCode {
	UNKNOWN, INVALID_ARGUMENTS, INVALID_HOSTNAMES_WHITELIST, INVALID_DATES_WHITELIST, INVALID_REFERECENCE_CSV,
	INVALID_NMON_LIST, OPENING_OUTPUTFILE, WRITTING_OUTPUTFILE, CLOSING_OUTPUTFILE, OPENING_REFFILE, INVALID_REFFILE,
	INVALID_NMON_FILE;
}
